version: '3.8'
services:
  postgres_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: projetweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: projetweb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./back
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:projetweb@postgres_db:5432/projetweb"
    depends_on:
      - postgres_db

  frontend:
    build: ./front
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  default:
